# Generated by Django 4.1.3 on 2025-01-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0002_genre_genre_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre_Book',
            new_name='BookGenre',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='description',
        ),
    ]
